In [1]:
import numpy as np
import tensorflow as tf

In [2]:
[1, 2, 3]

[1, 2, 3]

# Tensor 생성
* List 생성

array 생성
* tuple이나 list둘 다 np.array()로 씌어서 array를 만들 수 있음 

In [34]:
np.array([1,2,3])
arr.shape

(3,)

## Tensor 생성
tf.constant()
- list -> Tensor

In [8]:
tf.constant([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

tf.constant()
- list -> Tensor

In [10]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [12]:
tensor = tf.constant(arr)
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

Tensor에 담긴 정보 확인
* shape 확인

In [13]:
tensor.shape

TensorShape([3])

*data type확인
 - tensor 생성 할 때도 data type을 정해주지 않기 때문에 datatype에 대한 혼동이 올 수 있음
 - data type에 따라 모델의 무게나 성능차이에도 영향을 줄 수 있음

In [14]:
tensor.dtype

tf.int32

In [16]:
tensor = tf.constant([1, 2, 3], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [ ]:
data type 정의

In [ ]:
data type 변환 
 - Numpy에서 astype()을 주었듯이, tensorflow에서는 tf.cast사용

In [17]:
arr = np.array([1, 2, 3], dtype=np.float32)

In [19]:
arr.astype(np.uint8)

array([1, 2, 3], dtype=uint8)

In [20]:
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [21]:
tf.cast(tensor, dtype=tf.uint8)

<tf.Tensor: shape=(3,), dtype=uint8, numpy=array([1, 2, 3], dtype=uint8)>

In [22]:
tensor.numpy()

array([1., 2., 3.], dtype=float32)

In [23]:
np.array(tensor)

array([1., 2., 3.], dtype=float32)

type()를 사용하여 numpy array로 변환된 것 확인

In [24]:
type(tensor.numpy())

numpy.ndarray

#난수생성

numpy에서는 normal distribution을 기본적으로 생성
 np.random.randn()

In [26]:
 np.random.randn(15)

array([ 0.72497624, -0.36194232, -0.47501519, -0.64558149,  0.43186795,
       -0.13374561, -0.66026028, -1.78413419,  0.4144165 ,  0.60458048,
       -0.15553955, -1.3543844 , -1.89781683,  1.09163304,  0.06857804])

In [27]:
np.random.normal(15)

16.013877900423967

tf.random.normal
- normal distribution

In [30]:
tf.random.normal([3, 3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.4888541 ,  0.4309595 , -1.5334195 ],
       [ 0.723645  ,  0.8106281 , -0.47174156],
       [-1.8028567 ,  0.23670383,  0.49668252]], dtype=float32)>

In [31]:
tf.random.normal([4, 4])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 0.47980005,  0.03230889,  0.0864726 ,  0.40085652],
       [ 0.2067356 ,  0.28453   ,  0.5363289 ,  0.0855198 ],
       [-0.66073054,  0.78763217, -0.13084151, -2.1717756 ],
       [-1.106292  , -0.3289852 ,  0.2347816 , -0.91092736]],
      dtype=float32)>

In [32]:
np.random.normal([3, 3])

array([1.54686545, 2.90618864])

tf.random.uniform
- Uniform Distribution

In [33]:
tf.random.uniform([3, 3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.18633342, 0.602723  , 0.17484736],
       [0.3451439 , 0.08287239, 0.23720372],
       [0.43592334, 0.76568174, 0.83396935]], dtype=float32)>